[build.environment]
  HUGO_VERSION = "0.135.0"
  NODE_VERSION = "22"

[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[context.deploy-preview]
  command = "npm run build:preview"
